### ISSUE TITLE
[feature request] All devices turn on/off

### ISSUE THREAD

**Issue by MrReaL** [nattlip/com.jilles.x10#1]
Really missing this basic feature. Hopefully it can be implemented first in line. Maybe a idea for an card:

Turn housecode/all(selection) lights/appliance/all devices (selection) on/off (selection)

**Comment by nattlip** [comment]
i am moving hous now , have tho paint and reconnect all domotica in the new house, so no time these weeks. i even dont have heating

**Comment by MrReaL** [comment]
Take your time, no hurry. In the mean time, try: "Okay Homey, turn heating on"

**Comment by nattlip** [comment]
is implemented in beta sdk 2 version
