### ISSUE TITLE
[feature request] Device type

### ISSUE THREAD

**Issue by MrReaL** [nattlip/com.jilles.x10#2]
When adding a device the option to tell Homey it's an lamp etc. (same options for zwave products).

If i tell Homey to switch off the living room X10 devices are not switched because they are not registered as lamp.

**Comment by nattlip** [comment]
you could use the virtual device app for this i believe. is is not cleat to me how that is done in zwave somewhere under the hood , and in klika sdk1

**Comment by nattlip** [comment]
it is implemented in the beta sdk2 version of the app
